using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading;
using Soenneker.Utils.PooledStringBuilders;

namespace Soenneker.JsonSchema.ToCSharp.Internal;

// Compiles the supported union-matching rules once, while building the client.
internal sealed class SchemaMatcherEmitter(string ns, Func<JsonNode, string, JsonNode> resolve, CancellationToken ct)
{
    private readonly Dictionary<JsonNode, string> _names = new();
    private readonly List<JsonNode> _schemas = [];
    private readonly List<string> _regexes = [];
    private readonly List<string> _constants = [];
    internal bool HasMatchers => _schemas.Count != 0;

    internal string Register(JsonNode schema)
    {
        if (_names.TryGetValue(schema, out string? name)) return name;
        name = "Match" + _schemas.Count;
        _names.Add(schema, name);
        _schemas.Add(schema);
        return name;
    }
    internal string Finish()
    {
        using var code = new PooledStringBuilder(32768);
        code.AppendLine("// <auto-generated/>\n#nullable enable\nusing System.Text.Json;\nusing System.Text;\nusing System.Text.RegularExpressions;\nnamespace " + ns + ";\n\ninternal static partial class UnionMatchers\n{");
        // Register may append dependencies, including recursive references, while emitting.
        for (int i = 0; i < _schemas.Count; i++)
        {
            ct.ThrowIfCancellationRequested();
            JsonNode schema = _schemas[i];
            code.AppendLine("    internal static bool " + _names[schema] + "(JsonElement value, int depth = 0)\n    {");
            code.AppendLine("        if (depth > 256) throw new JsonException(\"Schema nesting limit exceeded.\");");
            code.Append(Emit(schema));
            code.AppendLine("    }");
        }
        for (int i = 0; i < _regexes.Count; i++)
            code.AppendLine("    [GeneratedRegex(" + CSharpNames.Literal(_regexes[i]) + ", RegexOptions.None, 1000)]\n    private static partial Regex Pattern" + i + "();");
        if (_constants.Count > 0)
        {
            for (int i = 0; i < _constants.Count; i++)
                code.AppendLine("    private static readonly JsonElement Constant" + i + " = ReadConstant(" + CSharpNames.Literal(_constants[i]) + ");");
            code.AppendLine("    private static JsonElement ReadConstant(string json)\n    {\n        var document = JsonDocument.Parse(json);\n        return document.RootElement.Clone();\n    }");
        }
        code.AppendLine("}");
        return code.ToString();
    }
    private string Call(JsonNode schema, string value = "value") => Register(schema) + "(" + value + ", depth + 1)";
    private static string Utf8(string text) => CSharpNames.Literal(text) + "u8";
    private static string Kind(string type) => type switch
    {
        "null" => "value.ValueKind == JsonValueKind.Null",
        "string" => "value.ValueKind == JsonValueKind.String",
        "object" => "value.ValueKind == JsonValueKind.Object",
        "array" => "value.ValueKind == JsonValueKind.Array",
        "boolean" => "value.ValueKind is JsonValueKind.True or JsonValueKind.False",
        "number" => "value.ValueKind == JsonValueKind.Number",
        "integer" => "value.ValueKind == JsonValueKind.Number && value.TryGetDecimal(out decimal integer) && decimal.Truncate(integer) == integer",
        _ => "false"
    };
    private string Constant(JsonNode? node)
    {
        return node?.GetValueKind() switch
        {
            null or JsonValueKind.Null => "value.ValueKind == JsonValueKind.Null",
            JsonValueKind.String => "value.ValueKind == JsonValueKind.String && value.ValueEquals(" + Utf8(node.GetValue<string>()) + ")",
            JsonValueKind.True => "value.ValueKind == JsonValueKind.True",
            JsonValueKind.False => "value.ValueKind == JsonValueKind.False",
            _ => ConstantComparison(node!)
        };
    }
    private string ConstantComparison(JsonNode node)
    {
        string json = node.ToJsonString();
        int index = _constants.IndexOf(json);
        if (index < 0) { index = _constants.Count; _constants.Add(json); }
        // Parse literal values once; no schema or matching rules are interpreted by the client.
        return "JsonElement.DeepEquals(value, Constant" + index + ")";
    }
    private string Emit(JsonNode schema)
    {
        using var code = new PooledStringBuilder(2048);
        if (schema is not JsonObject obj)
        {
            code.AppendLine("        return " + (schema.GetValueKind() == JsonValueKind.True ? "true" : "false") + ";");
            return code.ToString();
        }
        if (obj["$ref"] is JsonValue reference)
        {
            code.AppendLine("        return " + Call(resolve(schema, reference.GetValue<string>())) + ";");
            return code.ToString();
        }
        if (obj["type"] is { } type)
        {
            IEnumerable<string> types = type is JsonArray array ? array.Select(t => t!.GetValue<string>()) : [type.GetValue<string>()];
            code.AppendLine("        if (!(" + string.Join(" || ", types.Select(t => "(" + Kind(t) + ")")) + ")) return false;");
        }
        if (obj["pattern"] is JsonValue patternValue)
        {
            string pattern = patternValue.GetValue<string>();
            int regex = _regexes.IndexOf(pattern);
            if (regex < 0) { regex = _regexes.Count; _regexes.Add(pattern); }
            code.AppendLine("        if (value.ValueKind == JsonValueKind.String && !Pattern" + regex + "().IsMatch(value.GetString()!)) return false;");
        }
        if (obj.ContainsKey("const")) code.AppendLine("        if (!(" + Constant(obj["const"]) + ")) return false;");
        if (obj["enum"] is JsonArray values)
            code.AppendLine("        if (!(" + (values.Count == 0 ? "false" : string.Join(" || ", values.Select(v => "(" + Constant(v) + ")"))) + ")) return false;");
        if (obj["oneOf"] is JsonArray one)
            code.AppendLine("        if (" + string.Join(" + ", one.Select(s => "(" + Call(s!) + " ? 1 : 0)")) + " != 1) return false;");
        if (obj["anyOf"] is JsonArray any)
            code.AppendLine("        if (!(" + string.Join(" || ", any.Select(s => Call(s!))) + ")) return false;");
        if (obj["allOf"] is JsonArray all)
            foreach (JsonNode? branch in all) code.AppendLine("        if (!" + Call(branch!) + ") return false;");
        if (obj["not"] is { } not) code.AppendLine("        if (" + Call(not) + ") return false;");
        JsonObject? properties = obj["properties"] as JsonObject;
        JsonObject? patterns = obj["patternProperties"] as JsonObject;
        HashSet<string> required = (obj["required"] as JsonArray)?.Select(n => n!.GetValue<string>()).ToHashSet(StringComparer.Ordinal) ?? [];
        if (properties != null || required.Count > 0 || patterns != null || obj.ContainsKey("additionalProperties"))
        {
            code.AppendLine("        if (value.ValueKind == JsonValueKind.Object)\n        {");
            foreach (string member in required.Where(m => properties?.ContainsKey(m) != true))
                code.AppendLine("            if (!value.TryGetProperty(" + Utf8(member) + ", out _)) return false;");
            int index = 0;
            if (properties != null)
                // Reject an unrelated tagged branch before traversing any of its payload.
                foreach ((string name, JsonNode? member) in properties.OrderByDescending(p => p.Value is JsonObject o && (o.ContainsKey("enum") || o.ContainsKey("const"))))
                {
                    string variable = "p" + index++;
                    bool needed = required.Contains(name);
                    code.AppendLine("            if (" + (needed ? "!" : "") + "value.TryGetProperty(" + Utf8(name) + ", out var " + variable + ") " + (needed ? "||" : "&&") + " !" + Call(member!, variable) + ") return false;");
                }
            if (patterns?.Count > 0 || obj["additionalProperties"] is { } additional && additional.GetValueKind() != JsonValueKind.True)
            {
                code.AppendLine("            foreach (var property in value.EnumerateObject())\n            {");
                bool checkAdditional = obj["additionalProperties"] is { } a && a.GetValueKind() != JsonValueKind.True;
                if (checkAdditional)
                    code.AppendLine("                bool known = " + (properties?.Count > 0 ? string.Join(" || ", properties.Select(p => "property.NameEquals(" + Utf8(p.Key) + ")")) : "false") + ";");
                if (patterns != null)
                    foreach ((string pattern, JsonNode? rule) in patterns)
                    {
                        int regex = _regexes.IndexOf(pattern);
                        if (regex < 0) { regex = _regexes.Count; _regexes.Add(pattern); }
                        code.AppendLine("                if (Pattern" + regex + "().IsMatch(property.Name))\n                {\n" + (checkAdditional ? "                    known = true;\n" : "") + "                    if (!" + Call(rule!, "property.Value") + ") return false;\n                }");
                    }
                if (checkAdditional) code.AppendLine("                if (!known && !" + Call(obj["additionalProperties"]!, "property.Value") + ") return false;");
                code.AppendLine("            }");
            }
            code.AppendLine("        }");
        }
        if (obj["items"] is { } items && items is not JsonArray)
            code.AppendLine("        if (value.ValueKind == JsonValueKind.Array)\n            foreach (var item in value.EnumerateArray()) if (!" + Call(items, "item") + ") return false;");
        if (obj.ContainsKey("minimum") || obj.ContainsKey("maximum"))
        {
            code.AppendLine("        if (value.ValueKind == JsonValueKind.Number && value.TryGetDecimal(out decimal number))\n        {");
            if (obj["minimum"] is { } min) code.AppendLine("            if (number < " + min.GetValue<decimal>().ToString(CultureInfo.InvariantCulture) + "m) return false;");
            if (obj["maximum"] is { } max) code.AppendLine("            if (number > " + max.GetValue<decimal>().ToString(CultureInfo.InvariantCulture) + "m) return false;");
            code.AppendLine("        }");
        }
        if (obj.ContainsKey("minLength") || obj.ContainsKey("maxLength"))
        {
            code.AppendLine("        if (value.ValueKind == JsonValueKind.String)\n        {\n            int length = 0;\n            foreach (var rune in value.GetString()!.EnumerateRunes()) length++;");
            if (obj["minLength"] is { } minLength) code.AppendLine("            if (length < " + minLength.GetValue<int>() + ") return false;");
            if (obj["maxLength"] is { } maxLength) code.AppendLine("            if (length > " + maxLength.GetValue<int>() + ") return false;");
            code.AppendLine("        }");
        }
        if (obj["minItems"] is { } minItems) code.AppendLine("        if (value.ValueKind == JsonValueKind.Array && value.GetArrayLength() < " + minItems.GetValue<int>() + ") return false;");
        if (obj["maxItems"] is { } maxItems) code.AppendLine("        if (value.ValueKind == JsonValueKind.Array && value.GetArrayLength() > " + maxItems.GetValue<int>() + ") return false;");
        if (obj.ContainsKey("exclusiveMinimum") || obj.ContainsKey("exclusiveMaximum") || obj.ContainsKey("multipleOf"))
        {
            code.AppendLine("        if (value.ValueKind == JsonValueKind.Number && value.TryGetDecimal(out decimal boundNumber))\n        {");
            if (obj["exclusiveMinimum"] is { } min) code.AppendLine("            if (boundNumber <= " + min.GetValue<decimal>().ToString(CultureInfo.InvariantCulture) + "m) return false;");
            if (obj["exclusiveMaximum"] is { } max) code.AppendLine("            if (boundNumber >= " + max.GetValue<decimal>().ToString(CultureInfo.InvariantCulture) + "m) return false;");
            if (obj["multipleOf"] is { } multiple)
            {
                decimal divisor = multiple.GetValue<decimal>();
                if (divisor <= 0) throw new ArgumentException("multipleOf must be positive.");
                code.AppendLine("            if (boundNumber % " + divisor.ToString(CultureInfo.InvariantCulture) + "m != 0) return false;");
            }
            code.AppendLine("        }");
        }
        code.AppendLine("        return true;");
        return code.ToString();
    }
}
